### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by thiemowmde**
~~Note that this mentions #63 as already being merged!~~ Done.

The diff is massive (see https://github.com/wmde/DataTypes/compare/0.5.2...master), but there is really only one relevant change in the current master. Everything else is nothing but cleanup, code style, documentation, …

Please review https://gerrit.wikimedia.org/r/329491 and https://gerrit.wikimedia.org/r/329596 along with this (not technically required because Wikibase.git will not start using new releases automatically).

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Used in production and relied upon by a bunch of other packages that are as well. Definitely should be 1.0 at this point

**Comment by thiemowmde** [comment]
I was also thinking about a 1.0 release. The only reason why I wanted to wait is because of the MediaWiki binding in `DataType::getLabel`. I would love to get rid of this before tagging a 1.0. I made this an actual patch now, see #63.

**Comment by JeroenDeDauw** [comment]
Looks good. How about also dropping PHP < 5.5?

> the MediaWiki binding

I just went wtf when seeing QUnit in the travis config and realized this stuff is also still in this component... so far for being MW agnostic :) https://github.com/wmde/DataTypes/tree/master/js

Just the PHP is also good tho

**Comment by thiemowmde** [comment]
For PHP 5.5 see #64.

**Pull request merged**
