### PR TITLE
Update build

### PR DESCRIPTION
**Pull request by manicki**
Add package.json file and runs JS tests and linter using npm.

This removes libraries from the repo (now updated and installed using npm), and custom home-brew test runner (test are now run using karma).

JavaScript stuff is only run as a part of a single travis build, not all six of them (given the size of the component it does not really matter, so could be dropped if preferred).

### CODE REVIEW

**Comment by thiemowmde** [comment]
Uh, that's awesome! So much weird copy-pasta gone.

@manicki, do you think it makes sense to merge #72 first, and rebase this? I think this would help a little bit.

**Comment by manicki** [comment]
Honestly, I don't.

**Comment by thiemowmde** [comment]
I'm afraid I don't fully understand every detail going on in this patch. @manicki, can we talk?

**Comment by JeroenDeDauw** [comment]
> So much weird copy-pasta gone.

This used to be the MW standard actually, and people got very mad if you dared to use a package mawnager :) Which is also weird ofc

**Pull request merged**
