### PR TITLE
Drop DataType::getLabel and static Message class

### PR DESCRIPTION
**Pull request by thiemowmde**
I found two usages, and both can be replaced very easily, see https://gerrit.wikimedia.org/r/329596.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Cool, would be real nice to get rid of this. Might still be used elsewhere tho...

**Comment by JeroenDeDauw** [comment]
Sidenote: in the release PR you mentioned removing MW binding. It is not fully gone with this PR, you still have the message key. Not PHP binding, but still binding. And still conceptually odd to have this here...

**Comment by JeroenDeDauw** [comment]
Did not find any usage based on a quick look. This is structurally and conceptually similar, though not the same: https://github.com/JeroenDeDauw/ParamProcessor/issues/17

Would be good to check properly though. If neither SMW nor Maps (with their composer dependencies) use this, then this is OK. I suspect they don't be am not sure and need to run now.

**Comment by thiemowmde** [comment]
> Might still be used

I searched two places: my code base, which includes all relevant extensions, and GitHub. I could not find an other user of this.

> you still have the message key.

I see what you mean, but tend to disagree. This is nothing but a string. It can be used without knowing anything about MediaWiki.

> If neither SMW nor Maps […] use this

Given that replacements are [that trivial](https://gerrit.wikimedia.org/r/329596) I believe we should go ahead and just do this.

**Comment by JeroenDeDauw** [comment]
> I searched two places: my code base, which includes all relevant extensions, and GitHub. I could not find an other user of this.

Thanks

> Given that replacements are that trivial I believe we should go ahead and just do this.

I came to the same conclusion in the meanwhile

> I see what you mean, but tend to disagree. This is nothing but a string. It can be used without knowing anything about MediaWiki.

I just realized that the messages are also defined in this component (which makes sense if the keys are here). I was under the impression they where in Wikibase (which would be bad... but we did have something like this at some point...)

**Pull request merged**
