### PR TITLE
Make use of the …::class feature

### PR DESCRIPTION
**Pull request by thiemowmde**

### CODE REVIEW

**Comment by manicki** [comment]
As this extension has been migrated to gerrit, this change should have not been submitted here. I will sync the gerrit repository with this change as the PR is already merged.

**Comment by thiemowmde** [comment]
Thanks, @manicki!

**Comment by manicki** [comment]
Done in https://gerrit.wikimedia.org/r/#/c/381431/

**Comment by JeroenDeDauw** [comment]
I've added `[READ-ONLY]` to the repo description to make it stand out more. Also removed all write permissions on the repo. If that is not what you want, let me know, and I will undo that change.

**Comment by manicki** [comment]
Thanks @JeroenDeDauw!

**Comment by thiemowmde** [comment]
This repository should be turned into a redirect to https://github.com/wikimedia/mediawiki-extensions-DataTypes.

**Comment by JeroenDeDauw** [comment]
That is AFAIK not possible, at least not without doing some weird stuff. (Could move the wmf repo, then move this one to that location, delete it, and move the original wmf back to where it was. Would probably work, assuming the delete does not kill the redirects.)

**Comment by manicki** [comment]
I actually don't think such redirect is needed. Wouldn't making this repo read-only and clearly explaining where is the development happening now be enough to make it clear for the contributors where to go? Especially given the volume of contributions to this repo.
Packagist also does not list the repo any way, so people should not even find this place :)

Dropping this repo would also mean all development history apart from commits is gone (PR history etc).

**Comment by Ladsgroup** [comment]
I agree with @manicki, I think we should keep it for historical reasons.

**Pull request merged**
